version: '3.3'

services:
  backend:
    build: 
       context: ./DockerFilePython
       dockerfile: Dockerfile
    container_name: backpython
    volumes:
      - './BackEnd:/project/'
    #command: sh -c "while true; do sleep 1; done" 
    command: python3 /project/manage.py runserver 0:8000
    ports:
      - 8000:8000
    depends_on:
      - dbpostgre
  dbpostgre:
    build:
       context: ./DockerFileDB
       dockerfile: Dockerfile
    container_name: postgres12
    restart: always
    volumes:
      - './db:/var/lib/postgresql/'
    ports:
      - 5432:5432