# Generated by Django 3.2.6 on 2021-08-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorName', models.TextField()),
                ('FiscalNumber', models.TextField()),
                ('ContractNumbe', models.TextField()),
                ('StartDate', models.TextField()),
                ('EndDate', models.TextField()),
                ('CommPph', models.TextField()),
            ],
        ),
    ]
