FROM ubuntu:18.04

RUN apt update -y
RUN apt-get upgrade -y
RUN apt update -y
RUN apt install python3 -y
RUN apt install python3-pip -y
RUN apt install python3-dev -y
RUN apt install python3-distutils -y
RUN apt install python3-venv -y
RUN apt install tesseract-ocr -y
RUN apt install libtesseract-dev -y
RUN apt install mysql-server -y
RUN pip3 install --upgrade pip
RUN pip3 install pytesseract
RUN pip3 install tesseract
RUN pip3 install pdf2image
RUN pip3 install django -U
RUN apt-get install -y git curl wget
RUN apt-get install -y poppler-utils
RUN pip3 install psycopg2-binary
